const systemConstants = {
    PAGE_SIZE: 5,
    MERCHANT_LIST: 'Merchant list',
    NO_MERCHANT_FOUND: 'No merchants found.',
    ADD_MERCHANT: 'Add merchant',
    DELETE_MERCHANT_MSG: 'Are you sure you want to delete this merchant?',
    LOADING_MERCHANT: 'Loading merchant(s)...',
    MERCHANT_SAVED: 'Merchant successfully saved.',
    MERCHANT_SAVING_FAILED: 'Saving merchant failed. Please fill in all the fields.',
    LOADING_BIDS: 'Loading bids...',
    MERCHANT_NOT_FOUND: 'Merchant not found.',
    EDIT_MERCHANT_INFO: 'Edit merchant information',
    RETURN_TO_LIST: 'Return to merchant list',
    NEW_MERCHANT: 'Add new merchant',
    NO_BID_FOUND: 'No bids found for the merchants.',
    ID: 'ID',
    CAR_TITLE: 'Car Title',
    AMOUNT: 'Amount(£)',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    AVATAR: 'Avatar',
    EMAIL: 'Email Id',
    PHONE_NUMBER: 'Phone Number',
    PREMIUM: 'Premium',
    BIDS: 'Bids',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CREATED: 'Created',
    SUBMIT: 'Submit',
    PREVIOUS: 'Previous',
    NEXT: 'Next',
    VIEW_BIDS: 'View Bids',
    FIRST_NAME_TITLE: 'Please enter a first name',
    LAST_NAME_TITLE: 'Please enter a last name',
    AVATAR_URL_TITLE: 'Please enter an avatar url',
    EMAIL_TITLE: 'Please enter an email address',
    INVALID_EMAIL_MSG: 'Invalid email address',
    PHONE_TITLE: 'Please enter a phone number'
};
export default systemConstants;
